on:
  push:
    tags:
      - "*"

name: CI
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Verify commit signatures
        uses: nadock/verified_commits_check@v1
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: "${{ secrets.REGISTRY_DOMAIN }}/henkru/tuya-mqtt"
      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Slack notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: always()
